Requires python-pyinotify
$ gnome-abrt
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 58, in <module>
    from gnome_abrt.directory_problems import DirectoryProblemSource
  File
"/usr/lib64/python2.7/site-packages/gnome_abrt/directory_problems.py",
line 26, in <module>
ImportError: No module named pyinotify